# Generated by Django 5.2.4 on 2025-08-06 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('leave', '0002_holiday_leavetype_leaverequest_attachment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaverequest',
            name='attachment',
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='object_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
