# Generated by Django 5.2.4 on 2025-08-07 00:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_document_object_id'),
        ('leave', '0003_remove_leaverequest_attachment_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leaverequest',
            options={'ordering': ['-requested_at']},
        ),
        migrations.RemoveField(
            model_name='leaverequest',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='leaverequest',
            name='object_id',
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.document'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='requested_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('manager_approved', 'Approuvé par manager'), ('hr_approved', 'Approuvé par HR'), ('rejected', 'Rejeté'), ('taken', 'Pris')], default='pending', max_length=20),
        ),
    ]
