# Generated by Django 5.2.4 on 2025-08-07 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0004_alter_leaverequest_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
