# Generated by Django 5.2.5 on 2025-08-20 07:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_alter_document_status'),
        ('employee', '0003_employee_manager'),
        ('leave', '0005_leaverequest_is_read'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['start_date', 'status'], name='leave_leave_start_d_76f11f_idx'),
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['requested_at'], name='leave_leave_request_0bd844_idx'),
        ),
    ]
