# Generated by Django 5.2.5 on 2025-08-20 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=100, unique=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-computed_at'],
                'indexes': [models.Index(fields=['valid_until'], name='analytics_a_valid_u_9f9885_idx')],
            },
        ),
    ]
