# Generated by Django 5.2.4 on 2025-07-20 14:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('description', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.department')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('M', 'M'), ('F', 'F')], max_length=1)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(default='Ivorian', max_length=50)),
                ('contact', models.CharField(blank=True, max_length=100)),
                ('employment_type', models.CharField(help_text='e.g. Fonctionnaire or Agent contractuel', max_length=50, verbose_name="Type d'emploi")),
                ('position', models.CharField(blank=True, help_text='Job title or position', max_length=100)),
                ('date_joined', models.DateField(blank=True, help_text='Date of entry into service', null=True)),
                ('status', models.CharField(default='actif', help_text='Employment status (actif/inactif)', max_length=20)),
                ('origin_structure', models.CharField(blank=True, help_text='Original structure of appointment', max_length=100)),
                ('workplace', models.CharField(blank=True, help_text='Current workplace location', max_length=100)),
                ('region', models.CharField(blank=True, help_text='Region of assignment', max_length=50)),
                ('qualification_category', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('current_class', models.CharField(blank=True, help_text='e.g. 1ère classe, 2ème classe', max_length=20)),
                ('echelon', models.PositiveIntegerField(blank=True, help_text='Current echelon level', null=True)),
                ('department', models.ForeignKey(blank=True, help_text='Current department or structure', null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.department')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee', to=settings.AUTH_USER_MODEL)),
                ('grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.grade')),
            ],
        ),
    ]
