# Generated by Django 5.2.4 on 2025-07-24 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Current department or structure', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='employee.department'),
        ),
    ]
