# Generated by Django 5.2.5 on 2025-08-29 22:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_region_worksite_employee_primary_worksite_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='grade',
            options={'ordering': ['code']},
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['name'], name='employee_de_name_1adfec_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['last_name', 'first_name'], name='employee_em_last_na_9f0101_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['status'], name='employee_em_status_33d5fd_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['department'], name='employee_em_departm_e1e10e_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['grade'], name='employee_em_grade_i_a3e5c7_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['region'], name='employee_em_region_eb2fb8_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['date_joined'], name='employee_em_date_jo_14c646_idx'),
        ),
        migrations.AddIndex(
            model_name='grade',
            index=models.Index(fields=['code'], name='employee_gr_code_e1faa0_idx'),
        ),
        migrations.AddIndex(
            model_name='region',
            index=models.Index(fields=['active'], name='employee_re_active_b04dd5_idx'),
        ),
        migrations.AddIndex(
            model_name='worksite',
            index=models.Index(fields=['region'], name='employee_wo_region__c2dd83_idx'),
        ),
        migrations.AddIndex(
            model_name='worksite',
            index=models.Index(fields=['department'], name='employee_wo_departm_a786b7_idx'),
        ),
        migrations.AddIndex(
            model_name='worksite',
            index=models.Index(fields=['active'], name='employee_wo_active_91824a_idx'),
        ),
    ]
