# Generated by Django 5.2.5 on 2025-08-20 18:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locale', models.CharField(default='fr', max_length=10)),
                ('timezone', models.CharField(default='Africa/Abidjan', max_length=64)),
                ('theme', models.CharField(choices=[('system', 'Système'), ('light', 'Clair'), ('dark', 'Sombre')], default='system', max_length=10)),
                ('date_format', models.CharField(choices=[('YYYY-MM-DD', '2025-08-19'), ('DD/MM/YYYY', '19/08/2025'), ('MM/DD/YYYY', '08/19/2025')], default='YYYY-MM-DD', max_length=12)),
                ('two_factor_enabled', models.BooleanField(default=False)),
                ('quiet_start', models.TimeField(blank=True, null=True)),
                ('quiet_end', models.TimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
