# Generated by Django 5.2.4 on 2025-07-20 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('arrete', 'Arrêté'), ('certificat_medical', 'Certificat Médical'), ('autre', 'Autre')], max_length=50)),
                ('issuance_date', models.DateField(blank=True, null=True)),
                ('issued_by', models.CharField(blank=True, help_text='Issuing authority', max_length=100)),
                ('file', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('content_text', models.TextField(blank=True, help_text='Text content or link if no file')),
                ('status', models.CharField(choices=[('valide', 'Valide'), ('expiré', 'Expiré')], default='valide', max_length=20)),
            ],
        ),
    ]
