# Generated by Django 5.2.4 on 2025-08-06 20:09

import django.db.models.deletion
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='content_type',
            field=models.ForeignKey(
                default=1, 
                on_delete=django.db.models.deletion.CASCADE, 
                to='contenttypes.contenttype'
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='object_id',
            # FIXED: Changed from tuple to single integer
            field=models.PositiveBigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='uploaded_at',
            # FIXED: Removed invalid default value
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='content_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('arrete', 'Arrêté'), ('certificat_medical', 'Certificat Médical'), ('contrat', 'Contrat'), ('autre', 'Autre')], max_length=50),
        ),
        migrations.AlterField(
            model_name='document',
            name='issued_by',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]