# Generated by Django 5.2.4 on 2025-08-06 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_content_type_document_object_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='object_id',
            field=models.PositiveBigIntegerField(blank=True, default=1, null=True),
        ),
    ]
