# Generated by Django 5.2.4 on 2025-08-07 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_document_object_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('to_validate', 'À valider'), ('valide', 'Valide'), ('expiré', 'Expiré')], default='valide', max_length=20),
        ),
    ]
