# Generated by Django 5.2.4 on 2025-08-07 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('HR', 'HR Officer'), ('MANAGER', 'Manager'), ('EMP', 'Employee')], default='EMP', max_length=7),
        ),
    ]
