# Generated by Django 5.2.5 on 2025-08-17 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('HR', 'HR Officer'), ('MANAGER', 'Manager'), ('EMP', 'Employee'), ('AUDITOR', 'Auditor')], default='EMP', max_length=7),
        ),
    ]
