# Generated by Django 5.2.5 on 2025-08-17 16:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='object_type',
        ),
        migrations.AddField(
            model_name='auditlog',
            name='impersonator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_impersonations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='ip_address',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='m2m_added',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='m2m_removed',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='method',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='object_ct',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='object_pk',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='object_repr',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='path',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='request_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='severity',
            field=models.CharField(choices=[('INFO', 'INFO'), ('WARN', 'WARN'), ('CRITICAL', 'CRITICAL')], default='INFO', max_length=16),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='status_code',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='user_agent',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'CREATE'), ('UPDATE', 'UPDATE'), ('DELETE', 'DELETE'), ('LOGIN', 'LOGIN'), ('LOGOUT', 'LOGOUT'), ('PASSWORD_CHANGE', 'PASSWORD_CHANGE'), ('RUN_GENERATE', 'RUN_GENERATE'), ('RUN_CLOSE', 'RUN_CLOSE'), ('RUN_REOPEN', 'RUN_REOPEN'), ('DOC_DOWNLOAD', 'DOC_DOWNLOAD'), ('DOC_STATUS_CHANGE', 'DOC_STATUS_CHANGE')], max_length=32),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='changes',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['-timestamp'], name='audit_audit_timesta_901180_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action'], name='audit_audit_action_86e815_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['object_ct', 'object_pk'], name='audit_audit_object__00634c_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', 'timestamp'], name='audit_audit_user_id_e8be02_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['severity', 'timestamp'], name='audit_audit_severit_4d72db_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['request_id'], name='audit_audit_request_06fe30_idx'),
        ),
    ]
