# Generated by Django 5.2.4 on 2025-08-06 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_employee_department'),
        ('payroll', '0002_situationtype_payroll'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_type', models.CharField(choices=[('PERMANENT', 'Fonctionnaire (Permanent)'), ('CONTRACTUAL', 'Agent contractuel'), ('TEMPORARY', 'Temporaire')], help_text='Type of contract', max_length=50)),
                ('salary', models.DecimalField(decimal_places=2, help_text='Monthly salary in local currency', max_digits=10)),
                ('start_date', models.DateField(help_text='Contract start date')),
                ('end_date', models.DateField(blank=True, help_text='Contract end date, null for ongoing', null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('TERMINATED', 'Terminated')], default='ACTIVE', help_text='Contract status', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, help_text='Additional contract details, e.g., promotion or salary adjustment')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='employee.employee')),
            ],
            options={
                'ordering': ['-start_date'],
                'constraints': [models.UniqueConstraint(fields=('employee', 'start_date'), name='unique_employee_contract_start_date')],
            },
        ),
    ]
