# Generated by Django 5.2.5 on 2025-08-15 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_employee_manager'),
        ('payroll', '0003_contract'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContributionScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('ee_rate', models.DecimalField(decimal_places=4, max_digits=7)),
                ('er_rate', models.DecimalField(decimal_places=4, max_digits=7)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('cap', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('include_taxable_allowances', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='PayrollComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('kind', models.CharField(choices=[('EARNING', 'Earning'), ('DEDUCTION', 'Deduction'), ('EMPLOYER', 'Employer Charge')], default='EARNING', max_length=16)),
                ('taxable', models.BooleanField(default=True)),
                ('contributory', models.BooleanField(default=True)),
                ('percentage', models.DecimalField(blank=True, decimal_places=4, help_text='If fixed % of a base; else leave null', max_digits=7, null=True)),
                ('sequence', models.PositiveIntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='TaxTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(default='XX', max_length=2)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-valid_from'],
            },
        ),
        migrations.CreateModel(
            name='CompanyPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(default='XX', max_length=2)),
                ('proration_method', models.CharField(choices=[('CALENDAR', 'Calendar days'), ('WORKING', 'Working days')], default='CALENDAR', max_length=16)),
                ('active_contribs', models.ManyToManyField(blank=True, to='payroll.contributionscheme')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payroll.currency')),
                ('active_tax_table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payroll.taxtable')),
            ],
        ),
        migrations.CreateModel(
            name='PayrollRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('processed', 'Processed'), ('closed', 'Closed')], default='draft', max_length=16)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('company_policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payroll.companypolicy')),
            ],
            options={
                'ordering': ['-year', '-month'],
                'unique_together': {('company_policy', 'year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gross_pay', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('taxable_gross', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('employee_contrib', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('employer_contrib', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('income_tax', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('other_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_pay', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('finalized', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hash', models.CharField(blank=True, help_text='Checksum of content for audit', max_length=64)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payroll.currency')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='payroll.payrollrun')),
            ],
            options={
                'unique_together': {('run', 'employee')},
            },
        ),
        migrations.CreateModel(
            name='PayslipItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, default=1, max_digits=12)),
                ('rate', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payroll.payrollcomponent')),
                ('payslip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='payroll.payslip')),
            ],
            options={
                'ordering': ['component__sequence', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TaxBracket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lower', models.DecimalField(decimal_places=2, max_digits=12)),
                ('upper', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('rate', models.DecimalField(decimal_places=4, max_digits=7)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brackets', to='payroll.taxtable')),
            ],
            options={
                'ordering': ['lower'],
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('rate', models.DecimalField(decimal_places=8, max_digits=18)),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_rates', to='payroll.currency')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_rates', to='payroll.currency')),
            ],
            options={
                'unique_together': {('base', 'quote', 'date')},
            },
        ),
    ]
