# Generated by Django 5.2.5 on 2025-08-16 06:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_employee_manager'),
        ('payroll', '0004_contributionscheme_currency_payrollcomponent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='companypolicy',
            name='cutoff_day',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Day-of-month for payroll cutoff (1-28).', null=True),
        ),
        migrations.AddField(
            model_name='companypolicy',
            name='pay_day',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Target pay date day-of-month (1-28).', null=True),
        ),
        migrations.CreateModel(
            name='VariableInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, default=1, max_digits=12)),
                ('rate', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payroll.payrollcomponent')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variable_inputs', to='employee.employee')),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variables', to='payroll.payrollrun')),
            ],
            options={
                'ordering': ['employee_id', 'component__sequence', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RecurringComponentAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('percentage', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payroll.payrollcomponent')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_components', to='employee.employee')),
            ],
            options={
                'ordering': ['-active', 'component__sequence', 'id'],
                'unique_together': {('employee', 'component', 'start_date')},
            },
        ),
    ]
