# Generated by Django 5.2.5 on 2025-08-17 00:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0005_companypolicy_cutoff_day_companypolicy_pay_day_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companypolicy',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='payslip',
            options={'ordering': ['-created_at', '-updated_at']},
        ),
        migrations.AddField(
            model_name='companypolicy',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
