# Generated by Django 5.2.5 on 2025-08-17 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0006_alter_companypolicy_options_alter_payslip_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companypolicy',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
