# Generated by Django 5.2.5 on 2025-08-20 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_employee_manager'),
        ('payroll', '0007_alter_companypolicy_created_at'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['start_date', 'end_date'], name='payroll_con_start_d_c1277e_idx'),
        ),
        migrations.AddIndex(
            model_name='payslip',
            index=models.Index(fields=['run'], name='payroll_pay_run_id_445073_idx'),
        ),
        migrations.AddIndex(
            model_name='payslipitem',
            index=models.Index(fields=['payslip', 'component'], name='payroll_pay_payslip_d2c780_idx'),
        ),
    ]
