# Generated by Django 5.2.5 on 2025-08-21 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_alter_document_status'),
        ('payroll', '0008_contract_payroll_con_start_d_c1277e_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.document'),
        ),
    ]
