# Generated by Django 5.2.5 on 2025-08-23 11:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('kind', models.CharField(choices=[('BANK', 'Bank'), ('PAYROLL_ENGINE', 'External Payroll'), ('BIOMETRIC_GATEWAY', 'Biometric')], max_length=32)),
                ('scopes', models.JSONField(blank=True, default=list)),
                ('ip_allowlist', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('contact_emails', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
