# Generated by Django 5.2.4 on 2025-08-07 12:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notification_user_alter_notificationpreference_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpreference',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
