# Generated by Django 5.2.4 on 2025-07-20 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdministrativeSituation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situation_type', models.CharField(choices=[('sick_leave', 'Congé de maladie'), ('training', 'Training/Formation'), ('detachment', 'Détachement'), ('availability', 'Disponibilité'), ('exclusion', 'Exclusion Temporaire'), ('exit', 'Sortie de carrière')], max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('actif', 'Actif'), ('terminé', 'Terminé'), ('en attente', 'En attente')], default='actif', max_length=20)),
                ('tranche_1_start', models.DateField(blank=True, null=True)),
                ('tranche_1_end', models.DateField(blank=True, null=True)),
                ('tranche_2_start', models.DateField(blank=True, null=True)),
                ('tranche_2_end', models.DateField(blank=True, null=True)),
                ('tranche_3_start', models.DateField(blank=True, null=True)),
                ('tranche_3_end', models.DateField(blank=True, null=True)),
                ('training_details', models.CharField(blank=True, help_text='Type/duration of training if applicable', max_length=100)),
                ('training_location', models.CharField(blank=True, help_text='Location of training', max_length=50)),
                ('physical_control', models.BooleanField(blank=True, help_text='Physical control done (for verifying presence)', null=True)),
                ('resumption_date', models.DateField(blank=True, help_text='Date of return to work', null=True)),
                ('detachment_duration', models.CharField(blank=True, max_length=20)),
                ('availability_reason', models.CharField(blank=True, max_length=100)),
                ('exclusion_reason', models.CharField(blank=True, max_length=100)),
                ('exit_type', models.CharField(blank=True, help_text='Type of exit (death, resignation, retirement, etc.)', max_length=50)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
                ('justification', models.ForeignKey(blank=True, help_text='Supporting document ID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.document')),
            ],
        ),
    ]
