# Generated by Django 5.2.4 on 2025-07-23 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('situation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrativesituation',
            name='situation_type',
            field=models.CharField(choices=[('sick_leave', 'Congé de maladie'), ('training', 'Training/Formation'), ('detachment', 'Détachement'), ('availability', 'Disponibilité'), ('exclusion', 'Exclusion Temporaire'), ('resignation', 'Démission'), ('retirement', 'Retraite'), ('death', 'Décès'), ('maternity_leave', 'Congé de maternité'), ('parental_leave', 'Congé parental'), ('suspension', 'Suspension'), ('exit', 'Sortie de carrière')], max_length=50),
        ),
    ]
