# Generated by Django 5.2.4 on 2025-08-06 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_content_type_document_object_id_and_more'),
        ('employee', '0002_alter_employee_department'),
        ('payroll', '0002_situationtype_payroll'),
        ('situation', '0002_alter_administrativesituation_situation_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Situation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('actif', 'Actif'), ('terminé', 'Terminé'), ('en attente', 'En attente')], default='actif', max_length=20)),
                ('tranche_1_start', models.DateField(blank=True, null=True)),
                ('tranche_1_end', models.DateField(blank=True, null=True)),
                ('tranche_2_start', models.DateField(blank=True, null=True)),
                ('tranche_2_end', models.DateField(blank=True, null=True)),
                ('tranche_3_start', models.DateField(blank=True, null=True)),
                ('tranche_3_end', models.DateField(blank=True, null=True)),
                ('training_details', models.CharField(blank=True, max_length=100)),
                ('training_location', models.CharField(blank=True, max_length=50)),
                ('physical_control', models.BooleanField(blank=True, null=True)),
                ('resumption_date', models.DateField(blank=True, null=True)),
                ('detachment_duration', models.CharField(blank=True, max_length=20)),
                ('availability_reason', models.CharField(blank=True, max_length=100)),
                ('exclusion_reason', models.CharField(blank=True, max_length=100)),
                ('exit_type', models.CharField(blank=True, max_length=50)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.document')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
                ('situation_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.situationtype')),
            ],
        ),
    ]
