# Generated by Django 5.2.5 on 2025-08-15 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('situation', '0003_situation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='situation',
            options={'ordering': ['-start_date']},
        ),
        migrations.DeleteModel(
            name='AdministrativeSituation',
        ),
    ]
