# Generated by Django 5.2.5 on 2025-08-29 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_alter_document_options_and_more'),
        ('employee', '0005_alter_department_options_alter_grade_options_and_more'),
        ('payroll', '0009_contract_document'),
        ('situation', '0004_alter_situation_options_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='situation',
            index=models.Index(fields=['employee'], name='situation_s_employe_f6b716_idx'),
        ),
        migrations.AddIndex(
            model_name='situation',
            index=models.Index(fields=['situation_type'], name='situation_s_situati_2f5eae_idx'),
        ),
        migrations.AddIndex(
            model_name='situation',
            index=models.Index(fields=['status'], name='situation_s_status_f43f78_idx'),
        ),
        migrations.AddIndex(
            model_name='situation',
            index=models.Index(fields=['start_date'], name='situation_s_start_d_15eb3c_idx'),
        ),
        migrations.AddIndex(
            model_name='situation',
            index=models.Index(fields=['end_date'], name='situation_s_end_dat_e69351_idx'),
        ),
        migrations.AddIndex(
            model_name='situation',
            index=models.Index(fields=['resumption_date'], name='situation_s_resumpt_78a627_idx'),
        ),
    ]
